- type: job
  id: Prisoner
  name: job-name-prisoner
  description: job-description-prisoner
  playTimeTracker: JobPrisoner
  startingGear: PrisonerGear
  alwaysUseSpawner: true
  canBeAntag: true # Spacious - enable prisoner antag
#  whitelistRequired: true
  icon: "JobIconPrisoner"
  supervisors: job-supervisors-security
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      min: 21600
    - !type:CharacterLogicOrRequirement
      requirements:
        - !type:CharacterSpeciesRequirement
          inverted: true
          species:
            - Shadowkin
        - !type:CharacterTraitRequirement
          traits:
            - ShadowkinBlackeye
  special:
  # - !type:AddComponentSpecial # Spacious - remove PacifiedComponent from prisoners
  #   components:
  #     - type: Pacified
  - !type:AddImplantSpecial # Spacious - add tracking implant to prisoners
    implants: [ TrackingImplant ]

- type: startingGear
  id: PrisonerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    shoes: ClothingShoesColorBlack
    id: PrisonerPDA
    ears: ClothingHeadsetPrison #deltaV
  innerClothingSkirt: ClothingUniformJumpsuitPrisoner
